# Generated by Django 5.0.8 on 2026-02-01 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional de la categoría",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la categoría está activa",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Código interno único del producto",
                        max_length=50,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        help_text="Código de barras externo o generado",
                        max_length=100,
                        unique=True,
                        verbose_name="Código de barras",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de venta al público",
                        max_digits=10,
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Cantidad mínima antes de alertar",
                        verbose_name="Stock mínimo",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto está disponible para venta",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="productos.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["sku"], name="productos_sku_a62667_idx"),
                    models.Index(
                        fields=["codigo_barras"], name="productos_codigo__aa601e_idx"
                    ),
                    models.Index(
                        fields=["categoria", "activo"],
                        name="productos_categor_6d98d4_idx",
                    ),
                ],
            },
        ),
    ]
