# Generated by Django 5.0.8 on 2026-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                help_text="Código de barras externo o generado internamente (RP-XXXXXX)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Código de barras",
            ),
        ),
    ]
