# Generated by Django 5.0.8 on 2026-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_producto_codigo_barras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Código interno único del producto",
                max_length=50,
                unique=True,
                verbose_name="SKU",
            ),
        ),
    ]
