# Generated by Django 5.0.8 on 2026-03-20 15:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_producto_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="atributos",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Atributos específicos según el tipo de producto (marca, modelo, etc.)",
                verbose_name="Atributos Personalizados",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["atributos"], name="idx_productos_atributos"
            ),
        ),
    ]
