# Generated by Django 5.0.8 on 2026-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_producto_atributos_producto_idx_productos_atributos"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="atributos_configurados",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Definición de atributos personalizados para productos de esta categoría",
                verbose_name="Atributos Configurados",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="tipo_negocio",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("plasticos", "Plásticos / Envases"),
                    ("autopartes", "Autopartes / Repuestos"),
                    ("otro", "Otro"),
                ],
                default="general",
                help_text="Tipo de industria/negocio de esta categoría",
                max_length=50,
                verbose_name="Tipo de Negocio",
            ),
        ),
    ]
