# Generated by Django 5.0.8 on 2026-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_categoria_atributos_configurados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[("nuevo", "Nuevo"), ("usado", "Usado")],
                default="nuevo",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Marca"
            ),
        ),
    ]
