# Generated by Django 5.0.8 on 2026-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_alter_producto_imagen"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(
                fields=["fecha_modificacion", "id"],
                name="categorias_fecha_m_f2af67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["fecha_modificacion", "id"], name="productos_fecha_m_20462c_idx"
            ),
        ),
    ]
