# Generated by Django 5.0.8 on 2026-08-24 01:35

import apps.tenancy.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_categoria_origen_cloud_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen_miniatura",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="JPEG de 320 px generado a partir de la imagen. No se edita a mano.",
                null=True,
                upload_to=apps.tenancy.media.producto_thumb_upload_to,
                verbose_name="Miniatura",
            ),
        ),
    ]
