# Generated by Django 5.0.8 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0010_producto_imagen_miniatura"),
        ("sucursales", "0003_sucursal_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen_origen_url",
            field=models.URLField(
                blank=True,
                default="",
                editable=False,
                help_text="Ultima imagen_url del cloud descargada con exito. Solo POS local.",
                max_length=500,
                verbose_name="URL de origen de la imagen",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="origen_sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde nacio el producto, si nacio de una venta en sucursal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos_originados",
                to="sucursales.sucursal",
                verbose_name="Sucursal de origen",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="pendiente_revision",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Nacio como stub de una venta y todavia no se completo desde el portal.",
                verbose_name="Pendiente de revision",
            ),
        ),
    ]
