# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_producto_origen_cloud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='revision_cloud',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Revision ISO autoritativa del cloud para CAS de maestros.',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='producto',
            name='revision_cloud',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Revision ISO autoritativa del cloud para CAS de maestros.',
                max_length=64,
            ),
        ),
    ]
