# Generated by Django 5.2.17 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_categoria_producto_revision_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='inactivado_at',
            field=models.DateTimeField(blank=True, help_text='Instante de la última baja lógica.', null=True, verbose_name='Inactivada el'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='motivo_inactivacion',
            field=models.TextField(blank=True, default='', help_text='Motivo trazable de la última baja lógica.', verbose_name='Motivo de inactivación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='inactivado_at',
            field=models.DateTimeField(blank=True, help_text='Instante de la última baja lógica.', null=True, verbose_name='Inactivado el'),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_inactivacion',
            field=models.TextField(blank=True, default='', help_text='Motivo trazable de la última baja lógica.', verbose_name='Motivo de inactivación'),
        ),
    ]
