# Generated by Django 5.0.8 on 2026-04-28 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventas", "0005_venta_sucursal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rnc",
                    models.CharField(
                        help_text="Registro Nacional del Contribuyente. 9 u 11 dígitos sin guiones.",
                        max_length=11,
                        unique=True,
                        verbose_name="RNC",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre comercial"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "proveedor_actual",
                    models.CharField(
                        choices=[
                            ("mseller", "MSeller (PSFE)"),
                            ("nativo", "Librería nativa (dgii-ecf-py)"),
                        ],
                        default="mseller",
                        help_text="Implementación de EmisorECFInterface a usar para este RNC.",
                        max_length=20,
                        verbose_name="Proveedor actual",
                    ),
                ),
                (
                    "config_proveedor",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Datos específicos del proveedor activo. Para credenciales sensibles (API keys, contraseñas), guardar el NOMBRE de la variable de entorno, NO el valor. Ejemplo: {"api_key_env": "MSELLER_API_KEY_ROYAL", "endpoint": "https://ecf.mseller.app/api"}',
                        verbose_name="Configuración del proveedor",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emisor e-CF",
                "verbose_name_plural": "Emisores e-CF",
                "ordering": ["-activo", "razon_social"],
            },
        ),
        migrations.CreateModel(
            name="ECF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("31", "Factura de Crédito Fiscal Electrónico"),
                            ("32", "Factura de Consumo Electrónica"),
                            ("33", "Nota de Débito Electrónica"),
                            ("34", "Nota de Crédito Electrónica"),
                            ("41", "Comprobante de Compras Electrónico"),
                            ("43", "Comprobante de Gastos Menores Electrónico"),
                            ("44", "Comprobante de Regímenes Especiales Electrónico"),
                            ("45", "Comprobante Gubernamental Electrónico"),
                            ("46", "Comprobante para Exportaciones Electrónico"),
                            ("47", "Comprobante para Pagos al Exterior Electrónico"),
                        ],
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "encf",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Formato E + tipo + 10 dígitos. Asignado por el proveedor al emitir.",
                        max_length=13,
                        verbose_name="eNCF",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("EN_PROCESO", "En proceso"),
                            ("APROBADO", "Aprobado"),
                            ("APROBADO_CONDICIONAL", "Aprobado con observaciones"),
                            ("RECHAZADO", "Rechazado"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "track_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador asignado por el proveedor para seguimiento.",
                        max_length=100,
                        verbose_name="Track ID",
                    ),
                ),
                (
                    "codigo_seguridad",
                    models.CharField(
                        blank=True,
                        help_text="Asignado por DGII al aprobar. Se usa en el QR del ticket impreso.",
                        max_length=20,
                        verbose_name="Código de seguridad",
                    ),
                ),
                (
                    "proveedor_usado",
                    models.CharField(
                        choices=[
                            ("mseller", "MSeller (PSFE)"),
                            ("nativo", "Librería nativa (dgii-ecf-py)"),
                        ],
                        help_text="Snapshot al momento de emitir. Permite trazabilidad si el emisor cambia de proveedor a futuro.",
                        max_length=20,
                        verbose_name="Proveedor usado",
                    ),
                ),
                (
                    "xml_firmado",
                    models.TextField(
                        blank=True,
                        help_text="Copia local del XML enviado a DGII. Protege ante cambio futuro de PSFE.",
                        verbose_name="XML firmado",
                    ),
                ),
                (
                    "xml_respuesta",
                    models.TextField(
                        blank=True,
                        help_text="Respuesta cruda recibida de DGII (vía proveedor).",
                        verbose_name="XML respuesta DGII",
                    ),
                ),
                (
                    "intentos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Venta de origen. Null para tipo 34 que no proviene de anulación directa.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecfs",
                        to="facturacion_electronica.emisor",
                        verbose_name="Emisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-CF",
                "verbose_name_plural": "e-CFs",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="EventoECF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        help_text="Vacío si es el evento inicial de creación.",
                        max_length=25,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=25, verbose_name="Estado nuevo"),
                ),
                ("mensaje", models.TextField(blank=True, verbose_name="Mensaje")),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos asociados al evento (respuesta del proveedor, error, contexto).",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "ecf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="facturacion_electronica.ecf",
                        verbose_name="e-CF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento e-CF",
                "verbose_name_plural": "Eventos e-CF",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="ecf",
            index=models.Index(
                fields=["estado", "creado_en"], name="facturacion_estado_b24e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecf",
            index=models.Index(
                fields=["emisor", "tipo"], name="facturacion_emisor__7c8a95_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ecf",
            constraint=models.UniqueConstraint(
                condition=models.Q(("encf", ""), _negated=True),
                fields=("emisor", "encf"),
                name="unique_encf_por_emisor",
            ),
        ),
    ]
