# Generated by Django 5.0.8 on 2026-02-12 21:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("productos", "0001_initial"),
        ("ventas", "0004_venta_cliente_financiacioncooperativa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numero de Cotizacion"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(verbose_name="Fecha de Creacion"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuento_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Descuento Total",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONVERTIDA", "Convertida a Venta"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizacion_origen",
                        to="ventas.venta",
                        verbose_name="Venta Generada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotizacion",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Descuento (Monto)",
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "total_linea",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Linea"
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="cotizaciones.cotizacion",
                        verbose_name="Cotizacion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_cotizacion",
                        to="productos.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cotizacion",
                "verbose_name_plural": "Detalles de Cotizacion",
            },
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(
                fields=["numero_cotizacion"], name="cotizacione_numero__78ded7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(
                fields=["fecha_creacion"], name="cotizacione_fecha_c_1e3b4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cotizacion",
            index=models.Index(fields=["estado"], name="cotizacione_estado_468b01_idx"),
        ),
    ]
