# Generated by Django 5.2.17 on 2026-09-11 16:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# COT-008 / COT-015: preflight de datos (ver la migracion equivalente de ventas).
def _preflight(apps, schema_editor):
    alias = schema_editor.connection.alias
    violaciones = [
        ('Cotizacion', 'subtotal < 0', models.Q(subtotal__lt=Decimal('0.00'))),
        ('Cotizacion', 'descuento_total < 0',
         models.Q(descuento_total__lt=Decimal('0.00'))),
        ('Cotizacion', 'total < 0', models.Q(total__lt=Decimal('0.00'))),
        ('Cotizacion', 'CONVERTIDA sin venta',
         models.Q(estado='CONVERTIDA') & models.Q(venta__isnull=True)),
        ('Cotizacion', 'no CONVERTIDA con venta',
         ~models.Q(estado='CONVERTIDA') & models.Q(venta__isnull=False)),
        ('DetalleCotizacion', 'cantidad < 1', models.Q(cantidad__lt=1)),
        ('DetalleCotizacion', 'precio_unitario < 0.01',
         models.Q(precio_unitario__lt=Decimal('0.01'))),
        ('DetalleCotizacion', 'descuento_monto < 0',
         models.Q(descuento_monto__lt=Decimal('0.00'))),
        ('DetalleCotizacion', 'descuento_monto > subtotal',
         models.Q(descuento_monto__gt=models.F('subtotal'))),
        ('DetalleCotizacion', 'total_linea < 0',
         models.Q(total_linea__lt=Decimal('0.00'))),
    ]
    for model_name, descripcion, condicion in violaciones:
        modelo = apps.get_model('cotizaciones', model_name)
        infractoras = list(
            modelo.objects.using(alias).filter(condicion)
            .values_list('pk', flat=True)[:20]
        )
        if infractoras:
            raise RuntimeError(
                f'COT-008/015: cotizaciones.{model_name} en "{alias}" tiene '
                f'filas con {descripcion}: {infractoras}. Corregir antes de '
                f'migrar (o correr verificar_integridad_financiera).'
            )

    duplicados_legacy = list(
        apps.get_model('cotizaciones', 'Cotizacion').objects.using(alias)
        .filter(sucursal__isnull=True)
        .values('numero_cotizacion')
        .annotate(total=models.Count('pk'))
        .filter(total__gt=1)
        .values_list('numero_cotizacion', 'total')[:20]
    )
    if duplicados_legacy:
        raise RuntimeError(
            f'COT-010: cotizaciones.Cotizacion en "{alias}" tiene numeros '
            f'legacy duplicados: {duplicados_legacy}. Resolverlos antes de migrar.'
        )


def _sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_cliente_contado_singleton"),
        ("cotizaciones", "0002_cotizacion_sucursal_unique"),
        (
            "productos",
            "0011_producto_imagen_origen_url_producto_origen_sucursal_and_more",
        ),
        ("sucursales", "0003_sucursal_negocio"),
        ("ventas", "0008_venta_descuento_autorizacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="venta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizacion_origen",
                to="ventas.venta",
                verbose_name="Venta Generada",
            ),
        ),
        migrations.RunPython(_preflight, _sin_reversa),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="cotizacion_subtotal_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_total__gte", Decimal("0.00"))),
                name="cotizacion_descuento_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", Decimal("0.00"))),
                name="cotizacion_total_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estado", "CONVERTIDA"),
                        ("venta__isnull", False),
                    ),
                    models.Q(
                        models.Q(("estado", "CONVERTIDA"), _negated=True),
                        ("venta__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cotizacion_estado_venta_consistente",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", True)),
                fields=("numero_cotizacion",),
                name="unique_cotizacion_legacy_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gte", 1)),
                name="detallecotizacion_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", Decimal("0.01"))),
                name="detallecotizacion_precio_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_monto__gte", Decimal("0.00"))),
                name="detallecotizacion_descuento_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_monto__lte", models.F("subtotal"))),
                name="detallecotizacion_descuento_no_supera_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_linea__gte", Decimal("0.00"))),
                name="detallecotizacion_total_no_negativo",
            ),
        ),
    ]
