# Generated by Django 5.0.8 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico de sucursal. Ej: SD-001, STI-001",
                        max_length=20,
                        unique=True,
                        verbose_name="Codigo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo. Ej: Royal Plast - Sede Principal",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Direccion")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefono"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Sucursales inactivas no pueden operar el POS",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Clave para autenticacion en futuro sistema de sync",
                        max_length=64,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima Modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "ordering": ["codigo"],
            },
        ),
    ]
