# Generated by Django 5.0.8 on 2026-04-22 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="ultima_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima sincronizacion recibida"
            ),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="usuario_servicio",
            field=models.OneToOneField(
                blank=True,
                help_text="User dedicado cuyo token DRF autentica requests sync desde esta sucursal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sucursal_servicio",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario de servicio (API)",
            ),
        ),
    ]
