# Generated by Django 5.0.8 on 2026-06-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
        ("sucursales", "0002_sucursal_ultima_sync_sucursal_usuario_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="negocio",
            field=models.ForeignKey(
                blank=True,
                help_text="Negocio (tenant) al que pertenece esta sucursal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sucursales",
                to="negocios.negocio",
                verbose_name="Negocio",
            ),
        ),
    ]
