# Generated by Django 5.0.8 on 2026-08-21 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_alter_tenant_media_prefix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionImpersonacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_objetivo",
                    models.CharField(
                        help_text="Usuario operativo del tenant bajo el que se actuo.",
                        max_length=150,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="Ticket o razon declarada por el operador.",
                        max_length=300,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "inicio",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "expira",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vencimiento del token emitido.",
                        null=True,
                    ),
                ),
                (
                    "cierre",
                    models.DateTimeField(
                        blank=True,
                        help_text="Logout explicito de la sesion impersonada.",
                        null=True,
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        help_text="Actor global real que ejecuto la accion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonaciones",
                        to="tenancy.identity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impersonaciones",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_sesiones_impersonacion",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "inicio"],
                        name="tenancy_ses_tenant__220f75_idx",
                    ),
                    models.Index(
                        fields=["identity", "inicio"],
                        name="tenancy_ses_identit_52622f_idx",
                    ),
                ],
            },
        ),
    ]
