# Generated by Django 5.2.17 on 2026-09-10 11:11

import re

import django.utils.timezone
from django.db import migrations, models


def completar_estado_y_preflight(apps, schema_editor):
    Tenant = apps.get_model('tenancy', 'Tenant')
    alias = schema_editor.connection.alias
    filas = list(Tenant.objects.using(alias).all())
    rnc_vistos = {}
    for tenant in filas:
        esperado_db = f'tnt_{tenant.tenant_key}'
        esperado_media = f'{tenant.tenant_key}/'
        if tenant.db_name != esperado_db or tenant.media_prefix != esperado_media:
            raise RuntimeError(
                f'TEN identity preflight: {tenant.tenant_key} usa db_name/media '
                'no derivados. Revisar y migrar datos/blobs manualmente; esta '
                'migracion no reapunta un tenant.'
            )
        raw = (tenant.rnc or '').strip()
        if raw:
            canon = re.sub(r'\D', '', raw)
            if len(canon) != 9:
                raise RuntimeError(
                    f'Tenant {tenant.tenant_key} tiene RNC no canonizable a 9 digitos.'
                )
            if canon in rnc_vistos:
                raise RuntimeError(
                    f'Tenants {rnc_vistos[canon]} y {tenant.tenant_key} comparten '
                    f'RNC {canon}; resolver identidad antes de migrar.'
                )
            rnc_vistos[canon] = tenant.tenant_key
            tenant.rnc_canonico = canon
        tenant.estado_provisioning = 'ACTIVE' if tenant.activo else 'PENDING'
    Tenant.objects.using(alias).bulk_update(
        filas, ['rnc_canonico', 'estado_provisioning'],
    )


def sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_sesionimpersonacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="estado_provisioning",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("DB_READY", "Base creada"),
                    ("SCHEMA_READY", "Esquema migrado"),
                    ("TENANT_READY", "Datos tenant listos"),
                    ("CONTROL_READY", "Control plane listo"),
                    ("ACTIVE", "Activo"),
                    ("FAILED", "Fallido/reanudable"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="provisioning_actualizado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tenant",
            name="provisioning_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="provisioning_intentos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rnc_canonico",
            field=models.CharField(
                blank=True, editable=False, max_length=9, null=True, unique=True
            ),
        ),
        migrations.RunPython(completar_estado_y_preflight, sin_reversa),
    ]
