# Generated by Django 5.0.8 on 2026-04-08 20:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Caja 1, Caja Principal",
                        max_length=50,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripcion",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TurnoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Apertura",
                    ),
                ),
                (
                    "fondo_apertura",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Efectivo inicial en caja al abrir turno",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Fondo de Apertura",
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Cierre"
                    ),
                ),
                (
                    "monto_contado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lo que la cajera cuenta fisicamente al cerrar",
                        max_digits=12,
                        null=True,
                        verbose_name="Efectivo Contado",
                    ),
                ),
                (
                    "monto_esperado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculado: fondo + ventas_efectivo - retiros - gastos + ingresos",
                        max_digits=12,
                        null=True,
                        verbose_name="Efectivo Esperado",
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Positivo = sobrante, Negativo = faltante",
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas_apertura",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Apertura"
                    ),
                ),
                (
                    "notas_cierre",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Cierre"
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos",
                        to="caja.caja",
                        verbose_name="Caja",
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Puede ser el mismo cajero o un admin",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cerrado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cajero/a",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de Caja",
                "verbose_name_plural": "Turnos de Caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RETIRO", "Retiro de Efectivo"),
                            ("GASTO", "Gasto Menor"),
                            ("INGRESO", "Ingreso de Fondos"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Motivo del movimiento",
                        max_length=200,
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que autorizo via soft-login (requerido para retiros)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_caja_autorizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_caja_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="caja.turnocaja",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="turnocaja",
            index=models.Index(fields=["estado"], name="caja_turnoc_estado_a5d2f2_idx"),
        ),
        migrations.AddIndex(
            model_name="turnocaja",
            index=models.Index(
                fields=["fecha_apertura"], name="caja_turnoc_fecha_a_f98296_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="turnocaja",
            index=models.Index(
                fields=["usuario", "estado"], name="caja_turnoc_usuario_131206_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="turnocaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ABIERTO")),
                fields=("usuario",),
                name="unique_turno_abierto_por_usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="turnocaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ABIERTO")),
                fields=("caja",),
                name="unique_turno_abierto_por_caja",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocaja",
            index=models.Index(
                fields=["turno", "tipo"], name="caja_movimi_turno_i_4d6e4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientocaja",
            index=models.Index(fields=["fecha"], name="caja_movimi_fecha_1a1a7a_idx"),
        ),
    ]
