# Generated by Django 5.0.8 on 2026-04-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0001_initial"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caja",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal a la que pertenece esta caja. Null para instalaciones legacy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cajas",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
