# Generated by Django 5.0.8 on 2026-09-05 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisos', '0009_asignacion_unicidad_efectiva'),
        ('sucursales', '0003_sucursal_negocio'),
        ('sync', '0010_logsync_detalle_alter_logsync_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorNotificaciones',
            fields=[
                ('clave', models.CharField(default='default', max_length=20, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False)),
                ('activado_desde', models.DateTimeField(blank=True, null=True)),
                ('ultima_purga', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'notificaciones_motor'},
        ),
        migrations.CreateModel(
            name='EventoNotificable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=64)),
                ('fuente', models.CharField(default='sync', max_length=32)),
                ('clave_fuente', models.CharField(max_length=128)),
                ('titulo', models.CharField(max_length=180)),
                ('cuerpo', models.CharField(max_length=500)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('ruta', models.CharField(blank=True, default='', max_length=255)),
                ('ocurrido_en', models.DateTimeField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_notificables', to='sucursales.sucursal')),
            ],
            options={'db_table': 'notificaciones_eventos', 'ordering': ['-ocurrido_en', '-id']},
        ),
        migrations.CreateModel(
            name='DestinatarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta')], default='NORMAL', max_length=10)),
                ('push_habilitado', models.BooleanField(default=True)),
                ('leida_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='notificaciones.eventonotificable')),
            ],
            options={'db_table': 'notificaciones_destinatarios', 'ordering': ['-evento__ocurrido_en', '-id']},
        ),
        migrations.CreateModel(
            name='EventoSyncNotificacionProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero_evento', models.BooleanField(default=False)),
                ('evento_sync', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion_notificacion', to='sync.eventosync')),
            ],
            options={'db_table': 'notificaciones_sync_procesados'},
        ),
        migrations.CreateModel(
            name='ExcepcionNotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=64)),
                ('modo', models.CharField(choices=[('INCLUIR', 'Incluir'), ('EXCLUIR', 'Excluir')], max_length=10)),
                ('enviar_push', models.BooleanField(default=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'notificaciones_excepciones_usuario', 'ordering': ['tipo_evento', 'usuario__username']},
        ),
        migrations.CreateModel(
            name='ReglaNotificacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=64)),
                ('activa', models.BooleanField(default=True)),
                ('enviar_push', models.BooleanField(default=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_notificacion', to='permisos.rol')),
            ],
            options={'db_table': 'notificaciones_reglas_rol', 'ordering': ['tipo_evento', 'rol__nombre']},
        ),
        migrations.CreateModel(
            name='SuscripcionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('nombre_dispositivo', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('ultimo_exito_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'notificaciones_suscripciones_push', 'ordering': ['-actualizado_en']},
        ),
        migrations.CreateModel(
            name='EntregaPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida'), ('DESCARTADA', 'Descartada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('proximo_intento_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_hasta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, default='', max_length=500)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_push', to='notificaciones.destinatarionotificacion')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='notificaciones.suscripcionpush')),
            ],
            options={'db_table': 'notificaciones_entregas_push', 'ordering': ['proximo_intento_en', 'id']},
        ),
        migrations.AddIndex(model_name='eventonotificable', index=models.Index(fields=['tipo_evento', '-ocurrido_en'], name='notif_evento_tipo_fecha')),
        migrations.AddConstraint(model_name='eventonotificable', constraint=models.UniqueConstraint(fields=('fuente', 'clave_fuente', 'tipo_evento'), name='notif_evento_fuente_unica')),
        migrations.AddIndex(model_name='destinatarionotificacion', index=models.Index(fields=['usuario', 'leida_en'], name='notif_usuario_leida')),
        migrations.AddConstraint(model_name='destinatarionotificacion', constraint=models.UniqueConstraint(fields=('evento', 'usuario'), name='notif_destinatario_unico')),
        migrations.AddConstraint(model_name='excepcionnotificacionusuario', constraint=models.UniqueConstraint(fields=('usuario', 'tipo_evento'), name='notif_excepcion_usuario_tipo_unica')),
        migrations.AddConstraint(model_name='reglanotificacionrol', constraint=models.UniqueConstraint(fields=('rol', 'tipo_evento'), name='notif_regla_rol_tipo_unica')),
        migrations.AddIndex(model_name='entregapush', index=models.Index(fields=['estado', 'proximo_intento_en'], name='notif_entrega_estado_fecha')),
        migrations.AddConstraint(model_name='entregapush', constraint=models.UniqueConstraint(fields=('destinatario', 'suscripcion'), name='notif_entrega_dest_sus_unica')),
    ]
