# Generated by Django 5.0.8 on 2026-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0002_reglas_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventosyncnotificacionprocesado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PROCESADO", "Procesado"),
                    ("REINTENTO", "En reintento"),
                    ("FALLIDO", "Fallido"),
                ],
                db_index=True,
                default="PROCESADO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eventosyncnotificacionprocesado",
            name="intentos",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventosyncnotificacionprocesado",
            name="proximo_intento_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventosyncnotificacionprocesado",
            name="ultimo_error",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
