# Generated by Django 5.0.8 on 2026-02-12 21:35

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONTADO", "Contado"),
                            ("PERSONAL", "Personal"),
                            ("CORPORATIVO", "Corporativo"),
                        ],
                        default="PERSONAL",
                        max_length=20,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre / Razon Social"
                    ),
                ),
                (
                    "cedula_rnc",
                    models.CharField(
                        blank=True,
                        help_text="Cedula para personas, RNC para empresas",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Cedula / RNC",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Direccion"),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0 = sin credito",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Limite de Credito",
                    ),
                ),
                (
                    "condiciones_pago",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 30 dias, contado, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Condiciones de Pago",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creacion",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["cedula_rnc"], name="clientes_cedula__5b6bf0_idx"
                    ),
                    models.Index(
                        fields=["tipo", "activo"], name="clientes_tipo_317170_idx"
                    ),
                    models.Index(fields=["nombre"], name="clientes_nombre_4aa028_idx"),
                ],
            },
        ),
    ]
