# Generated by Django 5.0.8 on 2026-08-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_cliente_plazo_credito_dias"),
        ("sucursales", "0003_sucursal_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="origen_id_local",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="PK que tiene el cliente en la BD de su sucursal de origen.",
                null=True,
                verbose_name="ID local de origen",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="origen_sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se creo el cliente, si nacio en una sucursal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_originados",
                to="sucursales.sucursal",
                verbose_name="Sucursal de origen",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["origen_sucursal", "origen_id_local"],
                name="clientes_origen__a5b3db_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("origen_id_local__isnull", False),
                    ("origen_sucursal__isnull", False),
                ),
                fields=("origen_sucursal", "origen_id_local"),
                name="cliente_origen_unico_por_sucursal",
            ),
        ),
    ]
