# Generated by Django 5.0.8 on 2026-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_origen_id_local_cliente_origen_sucursal_and_more"),
        ("sucursales", "0003_sucursal_negocio"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["fecha_modificacion", "id"], name="clientes_fecha_m_1af5b0_idx"
            ),
        ),
    ]
