# Generated by Django 5.0.8 on 2026-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_clientes_fecha_m_1af5b0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="origen_cloud_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="PK de esta fila en la BD cloud. Identidad de sync; no se edita a mano.",
                null=True,
                unique=True,
                verbose_name="ID en cloud",
            ),
        ),
    ]
