# Generated by Django 5.0.8 on 2026-02-01 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_compra",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Compra"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(max_length=200, verbose_name="Proveedor"),
                ),
                ("fecha_compra", models.DateTimeField(verbose_name="Fecha de Compra")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Total",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Costo Unitario",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.compra",
                        verbose_name="Compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_compra",
                        to="productos.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Compra",
                "verbose_name_plural": "Detalles de Compra",
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_lote",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Lote"
                    ),
                ),
                (
                    "fecha_compra",
                    models.DateTimeField(db_index=True, verbose_name="Fecha de Compra"),
                ),
                (
                    "cantidad_inicial",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad Inicial",
                    ),
                ),
                (
                    "cantidad_actual",
                    models.IntegerField(verbose_name="Cantidad Actual"),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Costo Unitario",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="productos.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["fecha_compra", "id"],
            },
        ),
        migrations.CreateModel(
            name="AjusteInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MERMA", "Merma"),
                            ("DANO", "Daño"),
                            ("CONTEO", "Ajuste por Conteo"),
                            ("CORRECCION", "Corrección"),
                            ("DEVOLUCION", "Devolución"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        help_text="Positivo = agregar, Negativo = quitar",
                        verbose_name="Cantidad",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "fecha_ajuste",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Ajuste"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes_inventario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes",
                        to="inventario.lote",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Inventario",
                "verbose_name_plural": "Ajustes de Inventario",
                "ordering": ["-fecha_ajuste"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra Inicial"),
                            ("VENTA", "Venta"),
                            ("AJUSTE", "Ajuste Manual"),
                            ("ANULACION", "Anulación de Venta"),
                            ("MERMA", "Merma"),
                            ("DANO", "Daño"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        help_text="Positivo = entrada, Negativo = salida",
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "cantidad_anterior",
                    models.IntegerField(verbose_name="Cantidad Anterior"),
                ),
                ("cantidad_nueva", models.IntegerField(verbose_name="Cantidad Nueva")),
                (
                    "referencia_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Venta, Ajuste, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Referencia",
                    ),
                ),
                (
                    "referencia_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Referencia"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Movimiento"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_lote",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Lote",
                "verbose_name_plural": "Movimientos de Lote",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["numero_compra"], name="inventario__numero__6f937f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["fecha_compra"], name="inventario__fecha_c_d4488f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["producto", "fecha_compra"],
                name="inventario__product_82b659_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["cantidad_actual"], name="inventario__cantida_418629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientolote",
            index=models.Index(
                fields=["lote", "tipo"], name="inventario__lote_id_c32087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientolote",
            index=models.Index(
                fields=["fecha_creacion"], name="inventario__fecha_c_4242cf_idx"
            ),
        ),
    ]
