# Generated by Django 5.0.8 on 2026-02-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="numero_factura",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
