# Generated by Django 5.0.8 on 2026-02-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_compra_numero_factura"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="detalle_compra",
            field=models.OneToOneField(
                blank=True,
                help_text="Línea de compra que generó este lote",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lote",
                to="inventario.detallecompra",
                verbose_name="Detalle de Compra",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="fecha_compra",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Compra"
            ),
        ),
    ]
