# Generated by Django 5.0.8 on 2026-02-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_lote_detalle_compra_alter_compra_fecha_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="detalle_compra",
            field=models.OneToOneField(
                default=1,
                help_text="Línea de compra que generó este lote",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lote",
                to="inventario.detallecompra",
                verbose_name="Detalle de Compra",
            ),
            preserve_default=False,
        ),
    ]
