# Generated by Django 5.0.8 on 2026-04-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alter_lote_detalle_compra"),
        ("productos", "0006_producto_estado_producto_marca"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se registro la compra. Null para compras legacy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se registro la compra. Null para compras legacy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddIndex(
            model_name="lote",
            index=models.Index(
                fields=["sucursal", "producto"], name="inventario__sucursa_7e1583_idx"
            ),
        ),
    ]
