# Generated by Django 5.0.8 on 2026-08-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_compra_sucursal_lote_sucursal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="detalle_compra",
            field=models.OneToOneField(
                blank=True,
                help_text="Línea de compra que generó este lote. Null si la línea se corrigió y el lote quedó anulado (su historial se conserva).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lote",
                to="inventario.detallecompra",
                verbose_name="Detalle de Compra",
            ),
        ),
    ]
