# Generated by Django 5.2.17 on 2026-09-11 16:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# DB-CONSTRAINTS: preflight de datos (ver la migracion equivalente de ventas).
def _preflight(apps, schema_editor):
    alias = schema_editor.connection.alias
    violaciones = [
        ('Compra', 'total < 0', models.Q(total__lt=Decimal('0.00'))),
        ('DetalleCompra', 'cantidad < 1', models.Q(cantidad__lt=1)),
        ('DetalleCompra', 'costo_unitario < 0.01',
         models.Q(costo_unitario__lt=Decimal('0.01'))),
        ('Lote', 'cantidad_inicial < 1', models.Q(cantidad_inicial__lt=1)),
        ('Lote', 'costo_unitario < 0.01',
         models.Q(costo_unitario__lt=Decimal('0.01'))),
    ]
    for model_name, descripcion, condicion in violaciones:
        modelo = apps.get_model('inventario', model_name)
        infractoras = list(
            modelo.objects.using(alias).filter(condicion)
            .values_list('pk', flat=True)[:20]
        )
        if infractoras:
            raise RuntimeError(
                f'DB-CONSTRAINTS: inventario.{model_name} en "{alias}" tiene '
                f'filas con {descripcion}: {infractoras}. Corregir antes de '
                f'migrar (o correr verificar_integridad_financiera).'
            )


def _sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_alter_lote_detalle_compra"),
        (
            "productos",
            "0011_producto_imagen_origen_url_producto_origen_sucursal_and_more",
        ),
        ("sucursales", "0003_sucursal_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_preflight, _sin_reversa),
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", Decimal("0.00"))),
                name="compra_total_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecompra",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gte", 1)),
                name="detallecompra_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecompra",
            constraint=models.CheckConstraint(
                condition=models.Q(("costo_unitario__gte", Decimal("0.01"))),
                name="detallecompra_costo_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_inicial__gte", 1)),
                name="lote_cantidad_inicial_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="lote",
            constraint=models.CheckConstraint(
                condition=models.Q(("costo_unitario__gte", Decimal("0.01"))),
                name="lote_costo_positivo",
            ),
        ),
    ]
