# Generated by Django 5.0.8 on 2026-04-06 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_negocio",
                    models.CharField(
                        default="Mi Negocio",
                        max_length=200,
                        verbose_name="Nombre del negocio",
                    ),
                ),
                (
                    "rnc",
                    models.CharField(
                        blank=True,
                        help_text="Registro Nacional del Contribuyente",
                        max_length=20,
                        verbose_name="RNC",
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Direccion")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefono"
                    ),
                ),
                (
                    "email_negocio",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email del negocio"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo para tickets, PDFs y cotizaciones",
                        null=True,
                        upload_to="config/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "modulo_etiquetas_zebra",
                    models.BooleanField(
                        default=False,
                        help_text="Impresion de etiquetas con impresora Zebra LP 2824",
                        verbose_name="Etiquetas Zebra",
                    ),
                ),
                (
                    "modulo_financiacion_coop",
                    models.BooleanField(
                        default=False,
                        help_text="Modulo de ventas con financiacion cooperativa y PDF formal",
                        verbose_name="Financiacion Cooperativa",
                    ),
                ),
                (
                    "modulo_cotizaciones",
                    models.BooleanField(
                        default=True,
                        help_text="Crear cotizaciones y convertir a ventas",
                        verbose_name="Cotizaciones",
                    ),
                ),
                (
                    "modulo_impresion_termica",
                    models.BooleanField(
                        default=True,
                        help_text="Impresion de tickets en impresora termica 80mm",
                        verbose_name="Impresion Termica",
                    ),
                ),
                (
                    "modulo_barcode_scanner",
                    models.BooleanField(
                        default=True,
                        help_text="Soporte para escaner de codigo de barras en POS",
                        verbose_name="Escaner de Codigo de Barras",
                    ),
                ),
                (
                    "modulo_reportes_ondemand",
                    models.BooleanField(
                        default=True,
                        help_text="Generacion manual de reportes con filtros",
                        verbose_name="Reportes On-Demand",
                    ),
                ),
                (
                    "modulo_ecf",
                    models.BooleanField(
                        default=False,
                        help_text="Integracion con DGII para comprobantes fiscales electronicos",
                        verbose_name="Facturacion Electronica (e-CF)",
                    ),
                ),
                (
                    "modulo_dashboard",
                    models.BooleanField(
                        default=True,
                        help_text="Panel de metricas y KPIs",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "pago_efectivo",
                    models.BooleanField(default=True, verbose_name="Pago en Efectivo"),
                ),
                (
                    "pago_transferencia",
                    models.BooleanField(
                        default=True, verbose_name="Pago por Transferencia"
                    ),
                ),
                (
                    "pago_tarjeta",
                    models.BooleanField(default=False, verbose_name="Pago con Tarjeta"),
                ),
                (
                    "hora_cierre_automatico",
                    models.TimeField(
                        default="19:00",
                        help_text="Hora a la que se ejecuta el cierre de caja diario",
                        verbose_name="Hora de cierre automatico",
                    ),
                ),
                (
                    "dias_limite_anulacion",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Cantidad de dias despues de los cuales no se puede anular una venta",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Dias limite para anulacion",
                    ),
                ),
                (
                    "stock_minimo_default",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Stock minimo predeterminado al crear productos nuevos",
                        verbose_name="Stock minimo por defecto",
                    ),
                ),
                (
                    "prefijo_numero_venta",
                    models.CharField(
                        default="VTA",
                        help_text="Prefijo para numeros de venta (ej: VTA-20260406-00001)",
                        max_length=10,
                        verbose_name="Prefijo numero de venta",
                    ),
                ),
                (
                    "formato_codigo_barras",
                    models.CharField(
                        default="RP-XXXXXX",
                        help_text="Formato para codigos de barras generados internamente",
                        max_length=20,
                        verbose_name="Formato codigo de barras interno",
                    ),
                ),
                (
                    "permitir_inventario_negativo",
                    models.BooleanField(
                        default=True,
                        help_text="Permitir ventas cuando el stock es insuficiente (se registra en auditoria)",
                        verbose_name="Permitir inventario negativo",
                    ),
                ),
                (
                    "nombre_impresora_termica",
                    models.CharField(
                        blank=True,
                        help_text="Nombre exacto como aparece en Windows (ej: 2C-POS80-01)",
                        max_length=100,
                        verbose_name="Nombre impresora termica",
                    ),
                ),
                (
                    "nombre_impresora_zebra",
                    models.CharField(
                        blank=True,
                        help_text="Nombre exacto como aparece en Windows (ej: ZDesigner LP 2824)",
                        max_length=100,
                        verbose_name="Nombre impresora Zebra",
                    ),
                ),
                (
                    "texto_pie_ticket",
                    models.TextField(
                        blank=True,
                        default="Gracias por su compra",
                        help_text="Texto que aparece al final del ticket de venta",
                        verbose_name="Texto pie de ticket",
                    ),
                ),
                (
                    "imprimir_logo_ticket",
                    models.BooleanField(
                        default=True, verbose_name="Imprimir logo en ticket"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracion del Negocio",
                "verbose_name_plural": "Configuracion del Negocio",
            },
        ),
    ]
