# Generated by Django 5.0.8 on 2026-04-21 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracionnegocio",
            options={
                "verbose_name": "Configuracion del Negocio",
                "verbose_name_plural": "Configuraciones del Negocio",
            },
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="dias_limite_anulacion",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="hora_cierre_automatico",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="imprimir_logo_ticket",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="nombre_impresora_termica",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="nombre_impresora_zebra",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="permitir_inventario_negativo",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="prefijo_numero_venta",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="stock_minimo_default",
        ),
        migrations.RemoveField(
            model_name="configuracionnegocio",
            name="texto_pie_ticket",
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="dias_anulacion",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Cantidad de dias permitidos para anular una venta",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Dias para Anulacion",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="sucursal",
            field=models.OneToOneField(
                blank=True,
                help_text="Sucursal a la que pertenece esta configuracion. Null para instalaciones legacy sin sucursal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configuracion",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="formato_codigo_barras",
            field=models.CharField(
                default="RP-XXXXXX",
                help_text="Formato para generacion de codigos internos",
                max_length=20,
                verbose_name="Formato Codigo de Barras",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="modulo_barcode_scanner",
            field=models.BooleanField(
                default=True,
                help_text="Lector de codigos de barras en el POS",
                verbose_name="Scanner de Codigo de Barras",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="modulo_dashboard",
            field=models.BooleanField(
                default=True,
                help_text="Panel de control con metricas en tiempo real",
                verbose_name="Dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="modulo_ecf",
            field=models.BooleanField(
                default=False,
                help_text="Emision de comprobantes fiscales electronicos (Ley 32-23)",
                verbose_name="Facturacion Electronica (e-CF)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionnegocio",
            name="modulo_reportes_ondemand",
            field=models.BooleanField(
                default=True,
                help_text="Generacion de reportes personalizados",
                verbose_name="Reportes On-Demand",
            ),
        ),
    ]
