# Generated by Django 5.0.8 on 2026-04-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0002_alter_configuracionnegocio_options_and_more"),
        ("facturacion_electronica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="ecf_proveedor",
            field=models.CharField(
                choices=[
                    ("mseller", "MSeller (PSFE)"),
                    ("nativo", "Libreria nativa (dgii-ecf-py)"),
                ],
                default="mseller",
                help_text='Implementacion a usar cuando modulo_ecf esta activo. En Fase Inicial solo "mseller" esta disponible.',
                max_length=20,
                verbose_name="Proveedor e-CF",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="emisor_activo",
            field=models.ForeignKey(
                blank=True,
                help_text="Entidad fiscal que firma los e-CF de esta sucursal. Requerido si modulo_ecf=True.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configuraciones",
                to="facturacion_electronica.emisor",
                verbose_name="Emisor activo",
            ),
        ),
    ]
