# Generated by Django 5.0.8 on 2026-05-02 22:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0003_configuracionnegocio_ecf_proveedor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="itbis_incluido_en_precio",
            field=models.BooleanField(
                default=True,
                help_text="Si True, Producto.precio_venta ya incluye ITBIS y se desglosa al emitir e-CF (back-calculo: base = precio/(1+pct)). Si False, precio_venta es base imponible y el ITBIS se suma encima.",
                verbose_name="ITBIS incluido en precio de venta",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="itbis_porcentaje_global",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                help_text="Porcentaje de ITBIS aplicado por defecto a todos los productos. Se usa hasta que Producto tenga su propio campo itbis_pct para tasas diferenciadas (16%, exento, etc.).",
                max_digits=5,
                verbose_name="ITBIS % global",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="modo_contingencia",
            field=models.BooleanField(
                default=False,
                help_text="PLACEHOLDER FASE 2 — actualmente NO afecta el comportamiento. Cuando se implemente: si True, el POS emite NCF papel (serie B) en lugar de e-CF, durante el periodo en que DGII está caída más de 24h. Requiere notificación previa a DGII vía Oficina Virtual y plazo máximo 15 días. Al volver a False, se dispara comando que convierte los NCF papel del periodo en e-CF para enviar a DGII en los siguientes 30 días.",
                verbose_name="Modo contingencia (Fase 2)",
            ),
        ),
    ]
