# Generated by Django 5.0.8 on 2026-05-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuracion",
            "0004_configuracionnegocio_itbis_incluido_en_precio_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="permitir_inventario_negativo",
            field=models.BooleanField(
                default=False,
                help_text="Si True, el sistema no bloquea ventas aunque el stock sea insuficiente. Usar con precaucion, puede llevar a inconsistencias si no se controla bienel flujo de compras e ingresos de mercancia.",
                verbose_name="Permitir inventario negativo",
            ),
        ),
    ]
