# Generated by Django 5.0.8 on 2026-08-21 20:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0008_configuracionnegocio_cantidad_copias_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="descuento_motivo_modo",
            field=models.CharField(
                choices=[
                    ("NINGUNO", "No pedir motivo"),
                    ("OPCIONAL", "Pedir motivo, permitir dejarlo vacio"),
                    ("OBLIGATORIO", "Exigir motivo"),
                ],
                default="NINGUNO",
                help_text='Cuanto se le exige al supervisor al autorizar. En un negocio donde se regatea casi toda venta, pedir texto libre cada vez termina en 400 filas que dicen "descuento": por eso el default es no pedirlo.',
                max_length=12,
                verbose_name="Motivo del descuento",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="descuento_requiere_autorizacion",
            field=models.BooleanField(
                default=False,
                help_text="Si True, un descuento que supere la tolerancia no se puede cerrar sin la autorizacion de un supervisor.",
                verbose_name="Descuentos requieren autorizacion",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="descuento_tolerancia_monto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Descuento en pesos que el cajero puede aplicar sin pedir autorizacion. 0 = ninguno.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tolerancia de descuento (monto)",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="descuento_tolerancia_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Descuento como % del subtotal que el cajero puede aplicar sin pedir autorizacion. 0 = ninguno.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Tolerancia de descuento (%)",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnegocio",
            name="descuento_vigencia_minutos",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Cuanto vive el token de autorizacion antes de vencer.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Vigencia de la autorizacion de descuento (minutos)",
            ),
        ),
    ]
