# Generated by Django 5.0.8 on 2026-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0009_descuento_autorizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnegocio",
            name="conteo_ciego_caja",
            field=models.BooleanField(
                default=False,
                help_text="Si esta activo, el cajero NO ve el efectivo esperado hasta ingresar su conteo fisico (control interno: evita que ajuste el conteo al numero esperado). El admin siempre lo ve. Apagado por defecto: una instalacion existente se comporta igual que antes.",
                verbose_name="Conteo ciego de caja",
            ),
        ),
    ]
