# Generated by Django 5.2.17 on 2026-09-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0010_configuracionnegocio_conteo_ciego_caja"),
        ("sucursales", "0003_sucursal_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesorapidopos",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal dueña de este acceso. Vacio = acceso legacy global (visible en todas las sucursales); asignalo para acotarlo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesos_rapidos_pos",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
