# Generated by Django 5.0.8 on 2026-06-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("negocios", "0001_initial"),
        ("sucursales", "0003_sucursal_negocio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="Key"),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "core",
                    models.BooleanField(
                        default=False,
                        help_text="Core = siempre activo, no vendible.",
                        verbose_name="Es core",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modulo",
                "verbose_name_plural": "Modulos",
                "db_table": "modulos",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "modulos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planes",
                        to="suscripciones.modulo",
                        verbose_name="Modulos incluidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
                "db_table": "planes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SuscripcionNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "negocio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion",
                        to="negocios.negocio",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suscripciones",
                        to="suscripciones.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripcion de negocio",
                "verbose_name_plural": "Suscripciones de negocio",
                "db_table": "suscripciones_negocio",
            },
        ),
        migrations.CreateModel(
            name="NegocioModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incluido",
                    models.BooleanField(
                        default=True,
                        help_text="True = agregar sobre el plan; False = quitar del plan.",
                        verbose_name="Incluido",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negocio_overrides",
                        to="suscripciones.modulo",
                        verbose_name="Modulo",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos_override",
                        to="negocios.negocio",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Override de modulo (negocio)",
                "verbose_name_plural": "Overrides de modulo (negocio)",
                "db_table": "negocio_modulos",
                "unique_together": {("negocio", "modulo")},
            },
        ),
        migrations.CreateModel(
            name="SucursalModuloOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=False,
                        help_text="False = apagado en esta sucursal.",
                        verbose_name="Activo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursal_overrides",
                        to="suscripciones.modulo",
                        verbose_name="Modulo",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos_override",
                        to="sucursales.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Override de modulo (sucursal)",
                "verbose_name_plural": "Overrides de modulo (sucursal)",
                "db_table": "sucursal_modulo_overrides",
                "unique_together": {("sucursal", "modulo")},
            },
        ),
    ]
