# Generated by Django 5.2.17 on 2026-09-10 20:38

from django.db import migrations, models

# Composicion CONGELADA de la version 1 de cada tier, tal como estaba el dia
# de este backfill -- NO importar `apps.suscripciones.seed.TIERS` aca: esa
# constante sigue evolucionando (nuevas versiones) y esta migracion debe
# seguir comparando siempre contra la v1 original, sin importar que diga el
# codigo actual, para reproducir el mismo resultado en cualquier momento.
_TIERS_V1 = {
    'basico': {'impresion_termica', 'barcode_scanner'},
    'pro': {
        'impresion_termica', 'barcode_scanner', 'cuentas_por_cobrar',
        'cotizaciones', 'reportes_ondemand', 'dashboard', 'etiquetas_zebra',
    },
    'empresarial': {
        'impresion_termica', 'barcode_scanner', 'cuentas_por_cobrar',
        'cotizaciones', 'reportes_ondemand', 'dashboard', 'etiquetas_zebra',
        'ecf', 'financiacion',
    },
}


def backfill_preset_version(apps, schema_editor):
    """
    SUS-017 — antes de este campo, ningun plan tenia version registrada.
    Marcar los tres tiers conocidos como `preset_version=1` a ciegas
    silenciaria un drift real: si un admin ya les habia tocado los modulos a
    mano, `sync_modulos` (que a partir de ahora SI resincroniza) los
    pisaria sin que nadie lo pidiera. Por eso solo se marca `preset_version=1`
    al plan cuyo set de modulos ACTUAL coincide exacto con la v1 congelada
    arriba; el resto (incluida cualquier fila ausente) queda `None` —
    "personalizado" — que es el estado seguro: `sync_modulos` no lo toca
    hasta que un operador lo revise explicitamente.
    """
    Plan = apps.get_model('suscripciones', 'Plan')
    alias = schema_editor.connection.alias

    for slug, esperado in _TIERS_V1.items():
        plan = Plan.objects.using(alias).filter(slug=slug).first()
        if plan is None:
            continue
        actual = set(plan.modulos.using(alias).values_list('key', flat=True))
        if actual == esperado:
            plan.preset_version = 1
            plan.save(using=alias, update_fields=['preset_version'])


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0002_seed_suscripciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="preset_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="SUS-017 — version de `seed.TIERS` que este plan tiene aplicada. Vacio = plan personalizado: `manage.py sync_modulos` no lo toca. Un valor desactualizado respecto de TIERS se resincroniza (modulos + version) al correr sync_modulos.",
                null=True,
                verbose_name="Version del preset",
            ),
        ),
        migrations.RunPython(backfill_preset_version, migrations.RunPython.noop),
    ]
