# Generated by Django 5.0.8 on 2026-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("SYSADMIN", "Administrador de Sistema"),
                    ("ADMIN", "Administrador"),
                    ("CAJERA", "Cajera"),
                ],
                default="CAJERA",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
    ]
