# Generated by Django 5.0.8 on 2026-06-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
        ("usuarios", "0002_alter_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="negocio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="negocios.negocio",
                verbose_name="Negocio",
            ),
        ),
    ]
