# Generated by Django 5.0.8 on 2026-08-27 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
        ("usuarios", "0003_usuario_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="negocio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="negocios.negocio",
                verbose_name="Negocio",
            ),
        ),
    ]
