# Generated by Django 5.2.17 on 2026-09-10 11:00

import django.db.models.functions.text
from django.db import migrations, models


def verificar_colisiones_case_insensitive(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    alias = schema_editor.connection.alias
    for campo in ('username', 'email'):
        vistos = {}
        for pk, valor in Usuario.objects.using(alias).values_list('pk', campo).iterator():
            canon = (valor or '').strip().casefold()
            if canon in vistos:
                raise RuntimeError(
                    f'USR-016: colision case-insensitive en {alias}.{campo}: '
                    f'ids {vistos[canon]} y {pk}. Resolver manualmente antes '
                    f'de aplicar la constraint; la migracion no renombra usuarios.'
                )
            vistos[canon] = pk


def sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("negocios", "0001_initial"),
        ("usuarios", "0004_usuario_negocio_protect"),
    ]

    operations = [
        migrations.RunPython(verificar_colisiones_case_insensitive, sin_reversa),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="uniq_usuario_username_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uniq_usuario_email_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.CheckConstraint(
                condition=models.Q(("rol__in", ("SYSADMIN", "ADMIN", "CAJERA"))),
                name="usuario_rol_valido",
            ),
        ),
    ]
