# Generated by Django 5.0.8 on 2026-04-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionMaestro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tabla",
                    models.CharField(
                        choices=[
                            ("productos", "Productos"),
                            ("categorias", "Categorias"),
                            ("clientes", "Clientes"),
                            ("configuracion", "Configuracion"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Tabla",
                    ),
                ),
                (
                    "ultima_version",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp del registro mas reciente aplicado localmente.",
                        null=True,
                        verbose_name="Ultima version descargada",
                    ),
                ),
                (
                    "ultima_sync_exitosa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultima sync exitosa"
                    ),
                ),
                (
                    "registros_ultima_sync",
                    models.IntegerField(
                        default=0, verbose_name="Registros en ultima sync"
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de datos maestros",
                "verbose_name_plural": "Versiones de datos maestros",
                "ordering": ["tabla"],
            },
        ),
        migrations.CreateModel(
            name="EventoSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("VENTA_CREADA", "Venta creada"),
                            ("VENTA_ANULADA", "Venta anulada"),
                            ("CIERRE_CAJA", "Cierre de caja"),
                            ("APERTURA_CAJA", "Apertura de caja"),
                            ("AJUSTE_INVENTARIO", "Ajuste de inventario"),
                            ("COMPRA_REGISTRADA", "Compra registrada"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "objeto_referencia",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Ej: numero_venta. Util para buscar el evento de una venta sin abrir el payload.",
                        max_length=64,
                        verbose_name="Referencia del objeto",
                    ),
                ),
                (
                    "objeto_id_local",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="PK del objeto en la BD local. Util para debug.",
                        null=True,
                        verbose_name="ID local del objeto",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Datos serializados que se envian al cloud.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "hash_payload",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hex del payload. Permite idempotencia en el cloud.",
                        max_length=64,
                        verbose_name="Hash del payload",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("ERROR", "Error"),
                            ("DESCARTADO", "Descartado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "intentos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos de envio"
                    ),
                ),
                (
                    "ultimo_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Ultimo error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Enviado"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado por cloud"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sucursal origen del evento. Null para eventos legacy.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_sync",
                        to="sucursales.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de sync",
                "verbose_name_plural": "Eventos de sync",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["estado", "created_at"],
                        name="sync_evento_estado_74130a_idx",
                    ),
                    models.Index(
                        fields=["sucursal", "estado"],
                        name="sync_evento_sucursa_49e3e8_idx",
                    ),
                    models.Index(
                        fields=["tipo_evento", "estado"],
                        name="sync_evento_tipo_ev_3f97d1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push de eventos"),
                            ("PULL", "Pull de maestros"),
                            ("PING", "Verificar conexion"),
                            ("FULL", "Ciclo completo"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("EXITOSO", "Exitoso"),
                            ("PARCIAL", "Parcial (algunos fallos)"),
                            ("FALLO", "Fallo completo"),
                        ],
                        max_length=16,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "inicio",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Inicio"
                    ),
                ),
                (
                    "fin",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "duracion_ms",
                    models.IntegerField(default=0, verbose_name="Duracion (ms)"),
                ),
                (
                    "eventos_procesados",
                    models.IntegerField(default=0, verbose_name="Eventos procesados"),
                ),
                (
                    "eventos_exitosos",
                    models.IntegerField(default=0, verbose_name="Eventos exitosos"),
                ),
                (
                    "eventos_fallidos",
                    models.IntegerField(default=0, verbose_name="Eventos fallidos"),
                ),
                (
                    "registros_descargados",
                    models.IntegerField(
                        default=0, verbose_name="Registros descargados"
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(blank=True, default="", verbose_name="Mensaje"),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_sync",
                        to="sucursales.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de sync",
                "verbose_name_plural": "Logs de sync",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["-inicio"], name="sync_logsyn_inicio_c0c662_idx"
                    ),
                    models.Index(
                        fields=["tipo", "-inicio"], name="sync_logsyn_tipo_bfd0e8_idx"
                    ),
                ],
            },
        ),
    ]
