# Generated by Django 5.0.8 on 2026-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventosync",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("VENTA_CREADA", "Venta creada"),
                    ("VENTA_ANULADA", "Venta anulada"),
                    ("APERTURA_CAJA", "Apertura de caja"),
                    ("MOVIMIENTO_CAJA", "Movimiento de caja (retiro/gasto/ingreso)"),
                    ("CIERRE_CAJA", "Cierre de caja"),
                    ("AJUSTE_INVENTARIO", "Ajuste de inventario"),
                    ("COMPRA_REGISTRADA", "Compra registrada"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
