# Generated by Django 5.0.8 on 2026-08-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0005_inventory_sync_models_and_cursors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventosync",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("SIN_PAYLOAD", "Sin payload (serializar al enviar)"),
                    ("CONFIRMADO", "Confirmado"),
                    ("ERROR", "Error"),
                    ("DESCARTADO", "Descartado"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=16,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="eventosync",
            name="hash_payload",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hex del payload. Permite idempotencia en el cloud.",
                max_length=64,
                verbose_name="Hash del payload",
            ),
        ),
        migrations.AlterField(
            model_name="eventosync",
            name="payload",
            field=models.JSONField(
                blank=True,
                help_text="Datos serializados que se envian al cloud. Nulo si esta pendiente de serializar.",
                null=True,
                verbose_name="Payload",
            ),
        ),
    ]
