# Generated by Django 5.0.8 on 2026-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0006_alter_eventosync_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionmaestro",
            name="bloqueado_desde",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuando el cursor dejo de avanzar por un registro que falla.",
                null=True,
                verbose_name="Bloqueado desde",
            ),
        ),
        migrations.AddField(
            model_name="versionmaestro",
            name="bloqueado_detalle",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Que registro y que error estan frenando el cursor.",
                verbose_name="Detalle del bloqueo",
            ),
        ),
        migrations.AddField(
            model_name="versionmaestro",
            name="ultimo_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Desempate del cursor cuando varios registros comparten fecha.",
                verbose_name="Ultimo id aplicado",
            ),
        ),
    ]
