# Generated by Django 5.0.8 on 2026-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0009_dedup_ledger_compras"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsync",
            name="detalle",
            field=models.JSONField(blank=True, null=True, verbose_name="Detalle"),
        ),
        migrations.AlterField(
            model_name="logsync",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PUSH", "Push de eventos"),
                    ("PULL", "Pull de maestros"),
                    ("PING", "Verificar conexion"),
                    ("FULL", "Ciclo completo"),
                    ("CONCILIACION", "Conciliacion (anti-entropia)"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Tipo",
            ),
        ),
    ]
