# Generated by Django 5.2.17 on 2026-09-15

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_transporte_durable_bug_k'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutacionMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutacion_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID idempotente')),
                ('entidad', models.CharField(choices=[('PRODUCTO', 'Producto'), ('CATEGORIA', 'Categoria')], db_index=True, max_length=16)),
                ('entidad_id', models.PositiveIntegerField(db_index=True)),
                ('operacion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar')], max_length=16)),
                ('revision_base', models.CharField(blank=True, default='', help_text='Revision local observada antes de editar; vacia solo al crear.', max_length=64)),
                ('revision_resultante', models.CharField(blank=True, default='', max_length=64)),
                ('delta', models.JSONField(default=dict, help_text='Cambios JSON seguros: campo -> {before, after}.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de enviar'), ('ENVIANDO', 'Enviando'), ('CONFIRMADA', 'Confirmada por cloud'), ('CONFLICTO', 'Conflicto visible'), ('RECHAZADA', 'Rechazada por cloud')], db_index=True, default='PENDIENTE', max_length=16)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('sucursal_codigo', models.CharField(editable=False, max_length=40)),
                ('tenant_key', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('auditoria_event_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='event_id CT-01, no una FK mutable al historial.', null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('conflicto_detalle', models.TextField(blank=True, default='')),
                ('creado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('conflicto_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutaciones_maestro_locales', to='usuarios.usuario')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutaciones_maestro_locales', to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Mutacion local de maestro',
                'verbose_name_plural': 'Mutaciones locales de maestros',
                'ordering': ['creado_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mutacionmaestro',
            index=models.Index(fields=['sucursal', 'estado', 'creado_at'], name='sync_master_suc_est_idx'),
        ),
        migrations.AddIndex(
            model_name='mutacionmaestro',
            index=models.Index(fields=['entidad', 'entidad_id', 'estado'], name='sync_master_ent_est_idx'),
        ),
    ]
