# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_categoria_producto_revision_cloud'),
        ('sync', '0012_mutacion_maestro_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutacionmaestro',
            name='cloud_entidad_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mutacionmaestro',
            name='cloud_revision',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mutacionmaestro',
            name='codigo_resultado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mutacionmaestro',
            name='envio_expira_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mutacionmaestro',
            name='envio_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='mutacionmaestro',
            index=models.Index(
                fields=['sucursal', 'estado', 'envio_expira_at'],
                name='sync_master_send_idx',
            ),
        ),
    ]
