# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_mutacion_maestro_recepcion_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutacionmaestro',
            name='cloud_categoria_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
