# Generated by Django 5.2.17 on 2026-09-17 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0014_mutacion_maestro_cloud_categoria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolucionConflictoMaestro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CONSERVAR_CLOUD", "Conservar cloud"),
                            ("APLICAR_LOCAL", "Aplicar local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField()),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("cloud_revision_observada", models.CharField(max_length=64)),
                (
                    "cloud_revision_resultante",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "cloud_entidad_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("resuelto_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resoluciones_conflicto_maestro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mutacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolucion_conflicto",
                        to="sync.mutacionmaestro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolución de conflicto de maestro",
                "verbose_name_plural": "Resoluciones de conflictos de maestros",
            },
        ),
    ]
