# Generated by Django 5.2.17 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_resolucionconflictomaestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmaestro',
            name='tabla',
            field=models.CharField(
                choices=[
                    ('productos', 'Productos'),
                    ('categorias', 'Categorias'),
                    ('clientes', 'Clientes'),
                    ('configuracion', 'Configuracion'),
                    ('metodos_credito', 'Metodos de credito'),
                    ('roles', 'Roles'),
                    ('asignaciones', 'Asignaciones'),
                    ('resoluciones_conflicto', 'Resoluciones de conflictos de maestros'),
                ],
                max_length=32,
                unique=True,
                verbose_name='Tabla',
            ),
        ),
    ]
