# Generated by Django 5.2.17 on 2026-09-10 11:07

import re

from django.db import migrations, models


def completar_rnc_derivable(apps, schema_editor):
    Negocio = apps.get_model('negocios', 'Negocio')
    alias = schema_editor.connection.alias
    filas = list(Negocio.objects.using(alias).all())
    vistos = {}
    for negocio in filas:
        if not (negocio.nombre or '').strip() or not (negocio.slug or '').strip():
            raise RuntimeError(
                f'NEG-012/013: negocio id={negocio.pk} en {alias} tiene '
                'nombre o slug vacio. Corregir manualmente antes de migrar.'
            )
        raw = (negocio.rnc or '').strip()
        if not raw:
            negocio.rnc_canonico = None
            continue
        canon = re.sub(r'\D', '', raw)
        if len(canon) != 9:
            raise RuntimeError(
                f'NEG-011: negocio id={negocio.pk} en {alias} tiene RNC no '
                'canonizable a 9 digitos. La migracion no inventa el valor.'
            )
        if canon in vistos:
            raise RuntimeError(
                f'NEG-011: negocios {vistos[canon]} y {negocio.pk} en {alias} '
                f'comparten RNC canonico {canon}. Resolver antes de migrar.'
            )
        vistos[canon] = negocio.pk
        negocio.rnc_canonico = canon
    Negocio.objects.using(alias).bulk_update(filas, ['rnc_canonico'])


def sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="rnc_canonico",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Solo digitos; null cuando el negocio no tiene RNC.",
                max_length=9,
                null=True,
                unique=True,
                verbose_name="RNC canonico",
            ),
        ),
        migrations.RunPython(completar_rnc_derivable, sin_reversa),
        migrations.AddConstraint(
            model_name="negocio",
            constraint=models.CheckConstraint(
                condition=models.Q(("nombre", ""), _negated=True),
                name="negocio_nombre_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="negocio",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                name="negocio_slug_no_vacio",
            ),
        ),
    ]
