# Generated by Django 5.0.8 on 2026-03-14 17:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0003_alter_producto_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioValorizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(help_text="Fecha del inventario")),
                (
                    "datos_inventario",
                    models.JSONField(
                        help_text="Array de productos con lotes y valores FIFO"
                    ),
                ),
                (
                    "total_productos",
                    models.IntegerField(help_text="Cantidad de productos diferentes"),
                ),
                (
                    "total_unidades",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total de unidades en stock",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_total_inventario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total del inventario según FIFO",
                        max_digits=14,
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_pdf",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Inventario Valorizado",
                "verbose_name_plural": "Inventarios Valorizados",
                "db_table": "inventarios_valorizados",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha del día que se está cerrando", unique=True
                    ),
                ),
                (
                    "cantidad_ventas",
                    models.IntegerField(
                        default=0, help_text="Número de ventas del día"
                    ),
                ),
                (
                    "total_ventas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total vendido en el día",
                        max_digits=12,
                    ),
                ),
                (
                    "total_descuentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de descuentos aplicados",
                        max_digits=12,
                    ),
                ),
                (
                    "total_efectivo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_transferencia",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tarjeta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cantidad_anulaciones",
                    models.IntegerField(
                        default=0, help_text="Ventas anuladas en el día"
                    ),
                ),
                (
                    "total_anulaciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "resumen_cajeros",
                    models.JSONField(
                        default=dict, help_text="Detalle de ventas por cajero"
                    ),
                ),
                (
                    "generado_automaticamente",
                    models.BooleanField(
                        default=False,
                        help_text="True si fue generado por tarea automática",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de cuando se generó el reporte",
                    ),
                ),
                (
                    "archivo_pdf",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del PDF generado",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "cerrado",
                    models.BooleanField(
                        default=True, help_text="Indica si el cierre está finalizado"
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó el cierre (null si fue automático)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de Caja",
                "verbose_name_plural": "Cierres de Caja",
                "db_table": "cierres_caja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="TopProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "cantidad_vendida",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total de unidades vendidas",
                        max_digits=10,
                    ),
                ),
                (
                    "total_ventas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total en dinero generado",
                        max_digits=12,
                    ),
                ),
                (
                    "numero_transacciones",
                    models.IntegerField(
                        help_text="Número de ventas que incluyen este producto"
                    ),
                ),
                (
                    "margen_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Margen de ganancia promedio (%)",
                        max_digits=5,
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Producto",
                "verbose_name_plural": "Top Productos",
                "db_table": "top_productos",
                "ordering": ["-cantidad_vendida"],
                "indexes": [
                    models.Index(
                        fields=["fecha_inicio", "fecha_fin"],
                        name="top_product_fecha_i_074e99_idx",
                    )
                ],
            },
        ),
    ]
