"""
Alcance por sucursal, ciclo de vida del resumen diario e identidad de snapshots.

Cubre RPT-003 (sucursal en los snapshots), RPT-004 (BORRADOR/FINAL + version),
RPT-008 (el modelo se llama por lo que es), RPT-009 (margen real, costo
acumulado) y RPT-013 (unicidad de la identidad de cada snapshot).

Los indices unicos van PRECEDIDOS de una deduplicacion. `InventarioValorizado`
y `TopProducto` no tenian ninguna unicidad, y el manager hacia "buscar y luego
crear" sin lock: dos peticiones concurrentes podian dejar dos snapshots para la
misma fecha o rankings mezclados. Esas filas duplicadas existen en instalaciones
reales y harian fallar el ALTER.

Se deduplica en vez de abortar —al reves que en `sync.0008`— porque aca no hay
nada que perder: un snapshot es dato DERIVADO y regenerable, no un hecho. Se
conserva el mas reciente de cada grupo, que es el que ya venia ganando en la
practica.
"""

# Generated by Django 5.0.8 on 2026-08-21 04:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def deduplicar_snapshots(apps, schema_editor):
    """Deja un solo snapshot por identidad, conservando el mas reciente."""
    db = schema_editor.connection.alias

    Inventario = apps.get_model('reportes', 'InventarioValorizado')
    _dejar_el_ultimo(Inventario, db, ('fecha', 'sucursal_id'))

    Top = apps.get_model('reportes', 'TopProducto')
    _dejar_el_ultimo(
        Top, db, ('fecha_inicio', 'fecha_fin', 'producto_id', 'sucursal_id'),
    )


def _dejar_el_ultimo(Modelo, db, claves):
    vistos = set()
    a_borrar = []

    # `.using(db)` explicito: con DB-per-tenant el manager por defecto ruta por
    # el router, no por la conexion que el schema_editor esta migrando.
    filas = Modelo.objects.using(db).order_by('-id').values_list(
        'id', *claves,
    )
    for fila in filas.iterator(chunk_size=2000):
        identidad = fila[1:]
        if identidad in vistos:
            a_borrar.append(fila[0])
        else:
            vistos.add(identidad)

    for i in range(0, len(a_borrar), 500):
        Modelo.objects.using(db).filter(pk__in=a_borrar[i:i + 500]).delete()


def sin_reversa(apps, schema_editor):
    """Al revertir se quitan los indices; no hay nada que restaurar."""


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_categoria_origen_cloud_id"),
        ("reportes", "0002_cierrecaja_total_cobros_cxc"),
        ("sucursales", "0003_sucursal_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cierrecaja",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Resumen Diario de Ventas y Cobros",
                "verbose_name_plural": "Resumenes Diarios de Ventas y Cobros",
            },
        ),
        migrations.RemoveField(
            model_name="cierrecaja",
            name="cerrado",
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="diferencia_arqueo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Suma de faltantes/sobrantes de los turnos cerrados",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador (se recalcula)"),
                    ("FINAL", "Final (congelado)"),
                ],
                default="BORRADOR",
                help_text="BORRADOR se recalcula; FINAL queda congelado",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="fecha_calculo",
            field=models.DateTimeField(
                auto_now=True, help_text="Ultima vez que se recalcularon las cifras"
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal del resumen. Null = consolidado de todas, que solo puede generar quien tiene alcance global.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cierres_diarios",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="turnos_abiertos",
            field=models.IntegerField(
                default=0,
                help_text="Turnos que seguian abiertos al calcular. Mayor que cero significa que el dia no esta conciliado.",
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="turnos_cerrados",
            field=models.IntegerField(
                default=0, help_text="Turnos de caja cerrados en la fecha"
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Se incrementa en cada recalculo"
            ),
        ),
        migrations.AddField(
            model_name="inventariovalorizado",
            name="momento_corte",
            field=models.DateTimeField(
                blank=True,
                help_text="Instante exacto que representa el snapshot. Para una fecha pasada es el fin de ese dia; para hoy, el momento de generacion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventariovalorizado",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = consolidado de todas las sucursales",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventarios_valorizados",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="topproducto",
            name="costo_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Costo FIFO acumulado de las lineas del periodo",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="topproducto",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = consolidado de todas las sucursales",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_productos",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="fecha",
            field=models.DateField(help_text="Fecha del día que se está cerrando"),
        ),
        migrations.AlterField(
            model_name="topproducto",
            name="margen_promedio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Margen ponderado del periodo: (total_linea - costo_fifo) / total_linea * 100. Antes se persistia un 25.0 fijo de placeholder.",
                max_digits=6,
            ),
        ),
        migrations.RunPython(deduplicar_snapshots, sin_reversa),
        migrations.AddConstraint(
            model_name="cierrecaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", True)),
                fields=("fecha",),
                name="cierre_unico_consolidado_por_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="cierrecaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", False)),
                fields=("fecha", "sucursal"),
                name="cierre_unico_por_fecha_y_sucursal",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventariovalorizado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", True)),
                fields=("fecha",),
                name="inventario_unico_consolidado_por_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventariovalorizado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", False)),
                fields=("fecha", "sucursal"),
                name="inventario_unico_por_fecha_y_sucursal",
            ),
        ),
        migrations.AddConstraint(
            model_name="topproducto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", True)),
                fields=("fecha_inicio", "fecha_fin", "producto"),
                name="top_unico_consolidado_por_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="topproducto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sucursal__isnull", False)),
                fields=("fecha_inicio", "fecha_fin", "producto", "sucursal"),
                name="top_unico_por_periodo_y_sucursal",
            ),
        ),
    ]
