# Generated by Django 5.0.8 on 2026-06-10 16:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_por_cobrar", "0002_metodos_plazo_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentaporcobrar",
            name="interes_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cuentaporcobrar",
            name="monto_interes",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cuentaporcobrar",
            name="saldo_original",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="metodoplazocredito",
            name="interes_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Interes de financiamiento por defecto; editable por venta en el POS.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
