# Generated by Django 5.0.8 on 2026-08-21 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_por_cobrar", "0005_pago_anulacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocxc",
            name="clave_idempotencia",
            field=models.CharField(
                blank=True,
                help_text="UUID de la operacion de cobro. Un reintento con la misma clave devuelve el pago original en vez de crear otro.",
                max_length=64,
                null=True,
                verbose_name="Clave de idempotencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagocxc",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clave_idempotencia__isnull", False)),
                fields=("clave_idempotencia",),
                name="uniq_pagocxc_clave_idempotencia",
            ),
        ),
    ]
