# Generated by Django 5.0.8 on 2026-08-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_caja_origen_id"),
        ("cuentas_por_cobrar", "0006_pagocxc_clave_idempotencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocxc",
            name="turno_caja",
            field=models.ForeignKey(
                blank=True,
                help_text="Turno que recibio el efectivo. Null si no paso por caja.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_recibidos",
                to="caja.turnocaja",
                verbose_name="Turno de caja",
            ),
        ),
    ]
