# Generated by Django 5.0.8 on 2026-02-07 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cajero",
        ),
        migrations.AddField(
            model_name="venta",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
            preserve_default=False,
        ),
    ]
