# Generated by Django 5.0.8 on 2026-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_remove_venta_cajero_venta_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateTimeField(verbose_name="Fecha de Venta"),
        ),
    ]
