# Generated by Django 5.0.8 on 2026-02-12 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("ventas", "0003_alter_venta_fecha_venta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = Cliente Contado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.CreateModel(
            name="FinanciacionCooperativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_cliente",
                    models.CharField(max_length=200, verbose_name="Nombre del Cliente"),
                ),
                (
                    "cedula_cliente",
                    models.CharField(max_length=20, verbose_name="Cedula del Cliente"),
                ),
                (
                    "telefono_cliente",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefono del Cliente",
                    ),
                ),
                (
                    "direccion_cliente",
                    models.TextField(
                        blank=True, null=True, verbose_name="Direccion del Cliente"
                    ),
                ),
                (
                    "nombre_cooperativa",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Nombre de la Cooperativa",
                    ),
                ),
                (
                    "codigo_aprobacion",
                    models.CharField(
                        blank=True,
                        help_text="Codigo de aprobacion de la cooperativa",
                        max_length=50,
                        null=True,
                        verbose_name="Codigo de Aprobacion",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Adicionales"
                    ),
                ),
                (
                    "pdf_generado",
                    models.BooleanField(default=False, verbose_name="PDF Generado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financiaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financiacion",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financiacion Cooperativa",
                "verbose_name_plural": "Financiaciones Cooperativas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
