# Generated by Django 5.0.8 on 2026-04-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
        ("ventas", "0004_venta_cliente_financiacioncooperativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se realizo la venta. Null para ventas legacy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
