# Generated by Django 5.0.8 on 2026-08-21 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_pago_turno_caja"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="descuento_autorizacion_motivo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vacio si la configuracion no lo pide.",
                max_length=300,
                verbose_name="Motivo del descuento",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento_autorizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor que autorizo el descuento. Null si el descuento no requirio autorizacion.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="descuentos_autorizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Descuento autorizado por",
            ),
        ),
    ]
