# Generated by Django 5.2.17 on 2026-09-11 16:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# DB-CONSTRAINTS: preflight de datos. PostgreSQL valida las filas existentes al
# aplicar `ADD CONSTRAINT ... CHECK` y aborta con un error que no dice CUAL fila.
# Corremos la negacion de cada constraint como consulta ORM y levantamos un error
# accionable con las PKs infractoras. El comando
# `verificar_integridad_financiera` corre esto mismo antes de migrar.
def _preflight(apps, schema_editor):
    alias = schema_editor.connection.alias
    violaciones = [
        ('DetalleVenta', 'cantidad < 1', models.Q(cantidad__lt=1)),
        ('DetalleVenta', 'precio_unitario < 0.01',
         models.Q(precio_unitario__lt=Decimal('0.01'))),
        ('DetalleVenta', 'descuento_monto < 0',
         models.Q(descuento_monto__lt=Decimal('0.00'))),
        ('DetalleVenta', 'descuento_monto > subtotal',
         models.Q(descuento_monto__gt=models.F('subtotal'))),
        ('DetalleVenta', 'total_linea < 0',
         models.Q(total_linea__lt=Decimal('0.00'))),
        ('Pago', 'monto < 0.01', models.Q(monto__lt=Decimal('0.01'))),
        ('Venta', 'total < 0.01', models.Q(total__lt=Decimal('0.01'))),
        ('Venta', 'subtotal < 0', models.Q(subtotal__lt=Decimal('0.00'))),
        ('Venta', 'descuento_total < 0',
         models.Q(descuento_total__lt=Decimal('0.00'))),
    ]
    for model_name, descripcion, condicion in violaciones:
        modelo = apps.get_model('ventas', model_name)
        infractoras = list(
            modelo.objects.using(alias).filter(condicion)
            .values_list('pk', flat=True)[:20]
        )
        if infractoras:
            raise RuntimeError(
                f'DB-CONSTRAINTS: ventas.{model_name} en "{alias}" tiene filas '
                f'con {descripcion}: {infractoras}. Corregir antes de migrar '
                f'(o correr verificar_integridad_financiera).'
            )


def _sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_caja_origen_id"),
        ("clientes", "0006_cliente_contado_singleton"),
        (
            "productos",
            "0011_producto_imagen_origen_url_producto_origen_sucursal_and_more",
        ),
        ("sucursales", "0003_sucursal_negocio"),
        ("ventas", "0008_venta_descuento_autorizacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_preflight, _sin_reversa),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gte", 1)),
                name="detalleventa_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", Decimal("0.01"))),
                name="detalleventa_precio_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_monto__gte", Decimal("0.00"))),
                name="detalleventa_descuento_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_monto__lte", models.F("subtotal"))),
                name="detalleventa_descuento_no_supera_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_linea__gte", Decimal("0.00"))),
                name="detalleventa_total_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="pago",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gte", Decimal("0.01"))),
                name="pago_monto_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", Decimal("0.01"))),
                name="venta_total_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="venta_subtotal_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.CheckConstraint(
                condition=models.Q(("descuento_total__gte", Decimal("0.00"))),
                name="venta_descuento_no_negativo",
            ),
        ),
    ]
