# Generated by Django 5.2.17 on 2026-09-11 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_cliente_contado_singleton"),
        ("sucursales", "0003_sucursal_negocio"),
        ("ventas", "0009_detalleventa_detalleventa_cantidad_positiva_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="clave_idempotencia",
            field=models.CharField(
                blank=True,
                help_text="UUID de la operacion de venta. Un reintento con la misma clave devuelve la venta original en vez de crear otra.",
                max_length=64,
                null=True,
                verbose_name="Clave de idempotencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clave_idempotencia__isnull", False)),
                fields=("clave_idempotencia",),
                name="uniq_venta_clave_idempotencia",
            ),
        ),
    ]
