# Generated by Django 5.0.8 on 2026-06-08 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("negocios", "0001_initial"),
        ("sucursales", "0003_sucursal_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador de la accion. Ej: 'clientes.crear'.",
                        max_length=100,
                        unique=True,
                        verbose_name="Codigo",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "modulo",
                    models.CharField(
                        db_index=True,
                        help_text="Agrupacion para la UI. Ej: clientes, ventas.",
                        max_length=50,
                        verbose_name="Modulo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permisos",
                "ordering": ["modulo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador del rol dentro del negocio. Ej: cajero, admin.",
                        max_length=100,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Roles por defecto creados en el seed. Se protegen de borrado.",
                        verbose_name="Es de sistema",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificacion"
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="negocios.negocio",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="permisos.permiso",
                        verbose_name="Permisos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["negocio", "nombre"],
                "unique_together": {("negocio", "slug")},
            },
        ),
        migrations.CreateModel(
            name="AsignacionRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = aplica en todas las sucursales del negocio.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_rol",
                        to="sucursales.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_rol",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="permisos.rol",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignacion de rol",
                "verbose_name_plural": "Asignaciones de rol",
                "db_table": "asignaciones_rol",
                "unique_together": {("usuario", "rol", "sucursal")},
            },
        ),
    ]
