# Generated by Django 5.0.8 on 2026-08-21 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0004_cxc_permisos_granulares"),
        ("sucursales", "0003_sucursal_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizacionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "operacion",
                    models.CharField(
                        choices=[
                            ("credito.exceder_limite", "Exceder limite de credito"),
                            ("caja.retiro", "Retiro de caja"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto maximo que esta autorizacion cubre.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "alcance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Binding adicional, ej. {"cliente_id": 5}. El consumidor exige que coincida.',
                    ),
                ),
                ("motivo", models.CharField(max_length=300)),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
                ("expira", models.DateTimeField(db_index=True)),
                ("consumido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "consumido_referencia",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Que operacion la consumio (ej. numero_venta).",
                        max_length=64,
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides_autorizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to="sucursales.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorizacion de override",
                "verbose_name_plural": "Autorizaciones de override",
                "db_table": "permisos_autorizaciones_override",
                "ordering": ["-creado"],
            },
        ),
    ]
