# Generated by Django 5.0.8 on 2026-08-21 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0005_autorizacionoverride"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorizacionoverride",
            name="motivo",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="autorizacionoverride",
            name="operacion",
            field=models.CharField(
                choices=[
                    ("credito.exceder_limite", "Exceder limite de credito"),
                    ("caja.retiro", "Retiro de caja"),
                    ("ventas.descuento", "Aplicar descuento en venta"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CredencialFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Como reconocerla fisicamente. Ej: "Carnet supervisor - Ana".',
                        max_length=60,
                        verbose_name="Etiqueta",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "fecha_baja",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de baja"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credenciales_emitidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dada de alta por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credenciales_fisicas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial fisica",
                "verbose_name_plural": "Credenciales fisicas",
                "db_table": "permisos_credenciales_fisicas",
                "ordering": ["usuario", "-fecha_alta"],
            },
        ),
    ]
