# Generated by Django 5.0.8 on 2026-02-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("LOGIN_FAIL", "Intento de login fallido"),
                            ("CREATE", "Creación"),
                            ("UPDATE", "Edición"),
                            ("DELETE", "Eliminación"),
                            ("VIEW", "Visualización"),
                            ("PROD_CREATE", "Producto creado"),
                            ("PROD_UPDATE", "Producto editado"),
                            ("PROD_DELETE", "Producto eliminado"),
                            ("PRECIO_UPDATE", "Precio modificado"),
                            ("COMPRA_CREATE", "Compra registrada"),
                            ("LOTE_CREATE", "Lote creado"),
                            ("AJUSTE_INV", "Ajuste de inventario"),
                            ("VENTA_CREATE", "Venta realizada"),
                            ("VENTA_CANCEL", "Venta anulada"),
                            ("TICKET_PRINT", "Ticket impreso"),
                            ("TICKET_REPRINT", "Ticket reimpreso"),
                            ("USER_CREATE", "Usuario creado"),
                            ("USER_UPDATE", "Usuario modificado"),
                            ("USER_ENABLE", "Usuario activado"),
                            ("USER_DISABLE", "Usuario desactivado"),
                            ("PERM_ASSIGN", "Permiso asignado"),
                            ("PERM_REVOKE", "Permiso revocado"),
                            ("BACKUP_CREATE", "Backup creado"),
                            ("BACKUP_RESTORE", "Backup restaurado"),
                            ("CONFIG", "Configuración modificada"),
                            ("ERROR", "Error del sistema"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la acción",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del objeto"
                    ),
                ),
                (
                    "datos_anteriores",
                    models.JSONField(
                        blank=True,
                        help_text="Estado del objeto antes de la modificación",
                        null=True,
                        verbose_name="Datos anteriores",
                    ),
                ),
                (
                    "datos_nuevos",
                    models.JSONField(
                        blank=True,
                        help_text="Estado del objeto después de la modificación",
                        null=True,
                        verbose_name="Datos nuevos",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Información adicional relevante",
                        null=True,
                        verbose_name="Metadata adicional",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Navegador y sistema operativo",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "exito",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la acción se completó con éxito",
                        verbose_name="Acción exitosa",
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalle del error si la acción falló",
                        verbose_name="Mensaje de error",
                    ),
                ),
                (
                    "nivel_importancia",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        db_index=True,
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Nivel de importancia",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de objeto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción (null si fue el sistema)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-fecha_hora"],
                        name="auditoria_a_usuario_e64f3e_idx",
                    ),
                    models.Index(
                        fields=["accion", "-fecha_hora"],
                        name="auditoria_a_accion_b0af22_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="auditoria_a_content_4e6743_idx",
                    ),
                    models.Index(
                        fields=["-fecha_hora"], name="auditoria_a_fecha_h_b7616a_idx"
                    ),
                    models.Index(
                        fields=["nivel_importancia", "-fecha_hora"],
                        name="auditoria_a_nivel_i_370475_idx",
                    ),
                    models.Index(
                        fields=["exito", "-fecha_hora"],
                        name="auditoria_a_exito_ea5924_idx",
                    ),
                ],
            },
        ),
    ]
