# Generated by Django 5.0.8 on 2026-04-21 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sucursales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoria",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se genero este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_auditoria",
                to="sucursales.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["sucursal", "-fecha_hora"],
                name="auditoria_a_sucursa_7e5e2d_idx",
            ),
        ),
    ]
