# Generated by Django 5.0.8 on 2026-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0003_alter_auditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FAIL", "Intento de login fallido"),
                    ("CREATE", "Creación"),
                    ("UPDATE", "Edición"),
                    ("DELETE", "Eliminación"),
                    ("VIEW", "Visualización"),
                    ("PROD_CREATE", "Producto creado"),
                    ("PROD_UPDATE", "Producto editado"),
                    ("PROD_DELETE", "Producto eliminado"),
                    ("PRECIO_UPDATE", "Precio modificado"),
                    ("COMPRA_CREATE", "Compra registrada"),
                    ("LOTE_CREATE", "Lote creado"),
                    ("AJUSTE_INV", "Ajuste de inventario"),
                    ("VENTA_CREATE", "Venta realizada"),
                    ("VENTA_CANCEL", "Venta anulada"),
                    ("TICKET_PRINT", "Ticket impreso"),
                    ("TICKET_REPRINT", "Ticket reimpreso"),
                    ("DESC_AUTH", "Descuento autorizado"),
                    ("RECIBO_CXC_PRINT", "Recibo CxC impreso"),
                    ("PRINTER_TEST", "Prueba de impresora"),
                    ("USER_CREATE", "Usuario creado"),
                    ("USER_UPDATE", "Usuario modificado"),
                    ("USER_ENABLE", "Usuario activado"),
                    ("USER_DISABLE", "Usuario desactivado"),
                    ("PERM_ASSIGN", "Permiso asignado"),
                    ("PERM_REVOKE", "Permiso revocado"),
                    ("BACKUP_CREATE", "Backup creado"),
                    ("BACKUP_RESTORE", "Backup restaurado"),
                    ("CONFIG", "Configuración modificada"),
                    ("ERROR", "Error del sistema"),
                    ("CIERRE_DIARIO", "Resumen diario generado"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Acción",
            ),
        ),
    ]
