# Generated by Django 5.0.8 on 2026-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0004_alter_auditoria_accion"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoria",
            name="actor_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre visible tal como existia al momento del hecho.",
                max_length=300,
                verbose_name="Nombre (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="actor_tipo",
            field=models.CharField(
                choices=[("USUARIO", "Usuario"), ("SISTEMA", "Sistema")],
                default="SISTEMA",
                help_text="USUARIO = lo hizo una persona (aunque su cuenta ya no exista). SISTEMA = lo hizo un proceso automatico.",
                max_length=10,
                verbose_name="Tipo de actor",
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="actor_username",
            field=models.CharField(
                blank=True,
                help_text="Username tal como existia al momento del hecho.",
                max_length=150,
                verbose_name="Usuario (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="hash_integridad",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="SHA-256 de los campos inmutables del registro. Permite detectar una alteracion hecha por fuera de la aplicacion.",
                max_length=64,
                verbose_name="Hash de integridad",
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FAIL", "Intento de login fallido"),
                    ("CREATE", "Creación"),
                    ("UPDATE", "Edición"),
                    ("DELETE", "Eliminación"),
                    ("VIEW", "Visualización"),
                    ("PROD_CREATE", "Producto creado"),
                    ("PROD_UPDATE", "Producto editado"),
                    ("PROD_DELETE", "Producto eliminado"),
                    ("PRECIO_UPDATE", "Precio modificado"),
                    ("COMPRA_CREATE", "Compra registrada"),
                    ("LOTE_CREATE", "Lote creado"),
                    ("AJUSTE_INV", "Ajuste de inventario"),
                    ("VENTA_CREATE", "Venta realizada"),
                    ("VENTA_CANCEL", "Venta anulada"),
                    ("TICKET_PRINT", "Ticket impreso"),
                    ("TICKET_REPRINT", "Ticket reimpreso"),
                    ("DESC_AUTH", "Descuento autorizado"),
                    ("RECIBO_CXC_PRINT", "Recibo CxC impreso"),
                    ("PRINTER_TEST", "Prueba de impresora"),
                    ("USER_CREATE", "Usuario creado"),
                    ("USER_UPDATE", "Usuario modificado"),
                    ("USER_ENABLE", "Usuario activado"),
                    ("USER_DISABLE", "Usuario desactivado"),
                    ("PERM_ASSIGN", "Permiso asignado"),
                    ("PERM_REVOKE", "Permiso revocado"),
                    ("BACKUP_CREATE", "Backup creado"),
                    ("BACKUP_RESTORE", "Backup restaurado"),
                    ("CONFIG", "Configuración modificada"),
                    ("ERROR", "Error del sistema"),
                    ("CIERRE_DIARIO", "Resumen diario generado"),
                    ("AUDIT_PURGE", "Auditoria purgada por retencion"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Acción",
            ),
        ),
    ]
