# Generated by Django 5.0.8 on 2026-09-04 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0005_auditoria_inmutable_y_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoria",
            name="fecha_hora",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Fecha y hora",
            ),
        ),
    ]
