# Generated by Django 5.2.17 on 2026-09-10 10:48

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def crear_tabla_legacy_si_falta(apps, schema_editor):
    """
    Repara el caso real de una app que pasa a dual-home.

    Django pudo marcar 0001-0007 como aplicadas en el control plane cuando el
    router excluia ``auditoria``, sin crear la tabla. Antes de agregar campos,
    materializamos exactamente el modelo historico 0007 si aun no existe.
    """
    Auditoria = apps.get_model('auditoria', 'Auditoria')
    tablas = set(schema_editor.connection.introspection.table_names())
    if Auditoria._meta.db_table not in tablas:
        schema_editor.create_model(Auditoria)


def completar_derivables_legacy(apps, schema_editor):
    Auditoria = apps.get_model('auditoria', 'Auditoria')
    alias = schema_editor.connection.alias
    qs = Auditoria.objects.using(alias).all().only(
        'pk', 'fecha_hora', 'exito', 'actor_tipo',
    )
    for fila in qs.iterator(chunk_size=500):
        Auditoria.objects.using(alias).filter(pk=fila.pk).update(
            event_id=uuid.uuid4(),
            registrado_en=fila.fecha_hora,
            resultado='SUCCEEDED' if fila.exito else 'FAILED',
            actor_kind='USER' if fila.actor_tipo == 'USUARIO' else 'SYSTEM',
        )


def sin_reversa(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0007_alter_auditoria_accion"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sucursales", "0003_sucursal_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(crear_tabla_legacy_si_falta, sin_reversa),
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FAIL", "Intento de login fallido"),
                    ("CREATE", "Creación"),
                    ("UPDATE", "Edición"),
                    ("DELETE", "Eliminación"),
                    ("VIEW", "Visualización"),
                    ("PROD_CREATE", "Producto creado"),
                    ("PROD_UPDATE", "Producto editado"),
                    ("PROD_DELETE", "Producto eliminado"),
                    ("PRECIO_UPDATE", "Precio modificado"),
                    ("COMPRA_CREATE", "Compra registrada"),
                    ("LOTE_CREATE", "Lote creado"),
                    ("AJUSTE_INV", "Ajuste de inventario"),
                    ("VENTA_CREATE", "Venta realizada"),
                    ("VENTA_CANCEL", "Venta anulada"),
                    ("TICKET_PRINT", "Ticket impreso"),
                    ("TICKET_REPRINT", "Ticket reimpreso"),
                    ("DESC_AUTH", "Descuento autorizado"),
                    ("RECIBO_CXC_PRINT", "Recibo CxC impreso"),
                    ("COMPROBANTE_PDF", "Comprobante PDF emitido"),
                    ("PRINTER_TEST", "Prueba de impresora"),
                    ("USER_CREATE", "Usuario creado"),
                    ("USER_UPDATE", "Usuario modificado"),
                    ("USER_ENABLE", "Usuario activado"),
                    ("USER_DISABLE", "Usuario desactivado"),
                    ("PERM_ASSIGN", "Permiso asignado"),
                    ("PERM_REVOKE", "Permiso revocado"),
                    ("BACKUP_CREATE", "Backup creado"),
                    ("BACKUP_RESTORE", "Backup restaurado"),
                    ("CONFIG", "Configuración modificada"),
                    ("ERROR", "Error del sistema"),
                    ("CIERRE_DIARIO", "Resumen diario generado"),
                    ("AUDIT_PURGE", "Auditoria purgada por retencion"),
                ],
                db_index=True,
                max_length=100,
                verbose_name="Acción",
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="actor_kind",
            field=models.CharField(
                choices=[
                    ("USER", "Usuario"),
                    ("SERVICE", "Servicio"),
                    ("SYSTEM", "Sistema"),
                ],
                default="SYSTEM",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="actor_ref",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="branch_code",
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="branch_ref",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="canal",
            field=models.CharField(
                choices=[
                    ("POS_LOCAL", "POS local"),
                    ("PORTAL_API", "Portal API"),
                    ("SYNC", "Sincronizacion"),
                    ("COMMAND", "Comando"),
                    ("SYSTEM", "Sistema"),
                    ("LEGACY", "Productor legado"),
                ],
                default="LEGACY",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="correlacion_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="entity_display",
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="entity_ref",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="entity_type",
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="error_codigo",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="event_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="idempotencia_key",
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="impersonator_ref",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="registrado_en",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("SUCCEEDED", "Exitosa"),
                    ("DENIED", "Rechazada"),
                    ("FAILED", "Fallida"),
                ],
                default="SUCCEEDED",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="schema_version",
            field=models.CharField(
                db_index=True, default="audit.legacy.v0", editable=False, max_length=32
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="tenant_key",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.RunPython(completar_derivables_legacy, sin_reversa),
        migrations.AlterField(
            model_name="auditoria",
            name="event_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="registrado_en",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["tenant_key", "sucursal", "-fecha_hora"],
                name="auditoria_a_tenant__93285c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["entity_type", "entity_ref", "-fecha_hora"],
                name="auditoria_a_entity__4b8fe1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditoria",
            index=models.Index(
                fields=["correlacion_id", "-fecha_hora"],
                name="auditoria_a_correla_cc8b08_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditoria",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resultado__in", ("SUCCEEDED", "DENIED", "FAILED"))
                ),
                name="audit_resultado_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditoria",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "canal__in",
                        (
                            "POS_LOCAL",
                            "PORTAL_API",
                            "SYNC",
                            "COMMAND",
                            "SYSTEM",
                            "LEGACY",
                        ),
                    )
                ),
                name="audit_canal_valido",
            ),
        ),
    ]
